// Replacement baseline written during layout remediation; no historical pass count is reused.
import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { startFakeSshServer } from './fake-ssh-server.mjs'
import { connection, hostFixture, rendererFixture, until } from './integration-helpers.mjs'

test('real SSH terminal preserves split UTF-8, maps PTY and resize, and closes once', { timeout: 15000 }, async (t) => {
  const server = await startFakeSshServer()
  t.after(() => server.close())
  const renderer = rendererFixture()
  const { host } = await hostFixture(t, renderer.bridge)
  const opened = await host.openTerminal({ ...connection(server), cols: 111, rows: 37 })
  assert.equal(opened.host, '127.0.0.1')
  assert.deepEqual([opened.cols, opened.rows], [111, 37])
  await until(() => renderer.output(opened.sessionId).includes(Buffer.from('你好，世界\r\n')), 'split welcome bytes')
  host.input(opened.sessionId, '往返🙂\n')
  const expected = Buffer.from('你好，世界\r\necho:往返🙂\r\n')
  await until(() => renderer.output(opened.sessionId).length >= expected.length, 'terminal echo')
  assert.deepEqual(renderer.output(opened.sessionId), expected)
  assert.deepEqual([server.terminal.ptys[0].cols, server.terminal.ptys[0].rows], [111, 37])
  host.resize(opened.sessionId, 132, 42)
  await until(() => server.terminal.windows.length, 'remote window change')
  assert.deepEqual([server.terminal.windows[0].cols, server.terminal.windows[0].rows], [132, 42])
  host.close(opened.sessionId)
  host.close(opened.sessionId)
  await until(() => server.connections === 0, 'SSH socket closing')
  const closed = renderer.events.filter((event) => event.name === 'terminal:closed' && event.params[0] === opened.sessionId)
  assert.equal(closed.length, 1)
  assert.ok(closed[0].params[1].length > 0)
})

test('TOFU rejects unconfirmed keys, persists acceptance, and rejects changed keys at the same address', { timeout: 20000 }, async (t) => {
  const server = await startFakeSshServer({ greeting: false })
  t.after(() => server.close())
  const fixture = await hostFixture(t)
  await assert.rejects(fixture.host.openTerminal({ ...connection(server), acceptUnknownHostKey: false }), /首次连接/)
  assert.equal(existsSync(fixture.options.knownHostsFile), false)
  await fixture.host.openTerminal(connection(server))
  const known = JSON.parse(await readFile(fixture.options.knownHostsFile, 'utf8'))
  assert.equal(known.length, 1)
  assert.deepEqual([known[0].host, known[0].port, known[0].fingerprint], ['127.0.0.1', server.port, server.fingerprint])
  await fixture.host.dispose()
  const restarted = await fixture.create()
  await restarted.openTerminal({ ...connection(server), acceptUnknownHostKey: false })
  await restarted.dispose()
  await server.close()
  const changed = await startFakeSshServer({ port: server.port, greeting: false })
  t.after(() => changed.close())
  assert.notEqual(changed.fingerprint, server.fingerprint)
  const afterChange = await fixture.create()
  await assert.rejects(afterChange.openTerminal(connection(changed)), /主机密钥已改变/)
  const persisted = JSON.parse(await readFile(fixture.options.knownHostsFile, 'utf8'))
  assert.equal(persisted[0].fingerprint, server.fingerprint, 'rejection must not replace the trusted key')
})

test('saved credentials survive Host recreation without appearing in metadata or public records', { timeout: 15000 }, async (t) => {
  const server = await startFakeSshServer({ greeting: false })
  t.after(() => server.close())
  const renderer = rendererFixture()
  const fixture = await hostFixture(t, renderer.bridge)
  const saved = fixture.host.saveHost({ ...connection(server), label: ' 本机测试 ', rememberPassword: true })
  assert.equal(saved.label, '本机测试')
  assert.equal(saved.hasSecret, true)
  const metadata = await readFile(fixture.options.hostStoreFile, 'utf8')
  const secrets = await readFile(fixture.options.secretsFile, 'utf8')
  assert.ok(!metadata.includes(server.password))
  assert.ok(!metadata.includes('sealedSecret'))
  assert.ok(!JSON.stringify(saved).includes(server.password))
  assert.ok(!secrets.includes(server.password))
  await fixture.host.dispose()
  const restarted = await fixture.create()
  const records = restarted.listHosts()
  assert.equal(records.length, 1)
  assert.deepEqual(
    [records[0].id, records[0].label, records[0].host, records[0].port, records[0].username, records[0].authMethod, records[0].hasSecret],
    [saved.id, '本机测试', '127.0.0.1', server.port, 'demo', 'password', true],
  )
  const { password: _password, ...request } = connection(server)
  const session = await restarted.openTerminal({ ...request, hostId: saved.id })
  assert.ok(session.sessionId)
  assert.equal(restarted.removeHost(saved.id), true)
  assert.equal(restarted.removeHost(saved.id), false)
  assert.deepEqual(JSON.parse(await readFile(fixture.options.secretsFile, 'utf8')), {})
  assert.deepEqual(JSON.parse(await readFile(fixture.options.hostStoreFile, 'utf8')), [])
})

test('authentication and missing renderer failures leave no tracked SSH session', { timeout: 15000 }, async (t) => {
  const server = await startFakeSshServer({ greeting: false })
  t.after(() => server.close())
  const renderer = rendererFixture()
  const { host } = await hostFixture(t, renderer.bridge)
  await assert.rejects(host.openTerminal({ ...connection(server), password: 'incorrect-test-password' }), /认证失败/)
  assert.equal(host.internals.ctx.ssh.size, 0)
  assert.equal(host.internals.ctx.terminal.size, 0)
  assert.ok(renderer.events.some((event) => event.name === 'terminal:closed' && /认证失败/.test(event.params[1])))
  await until(() => server.connections === 0, 'failed authentication socket cleanup')
  renderer.disconnect()
  await assert.rejects(host.openTerminal(connection(server)), /渲染进程不可用/)
  assert.equal(server.connections, 0)
})

test('Host disposal unloads active terminal and SSH services and releases every socket', { timeout: 15000 }, async (t) => {
  const server = await startFakeSshServer({ files: { '/home/demo/readme.txt': 'hello' } })
  t.after(() => server.close())
  const { host } = await hostFixture(t)
  const [first] = await Promise.all([host.openTerminal(connection(server)), host.openTerminal(connection(server))])
  await host.sftpList(first.sessionId, '.')
  const ssh = host.internals.ctx.ssh
  const terminal = host.internals.ctx.terminal
  assert.equal(ssh.size, 2)
  assert.equal(terminal.size, 2)
  await host.dispose()
  await host.dispose()
  assert.equal(host.internals.disposed, true)
  assert.equal(ssh.size, 0)
  assert.equal(terminal.size, 0)
  await until(() => server.connections === 0, 'Host disposal socket cleanup')
})
